DROP INDEX IF EXISTS files_embedding_hnsw_idx;
ALTER TABLE files DROP COLUMN IF EXISTS embedding;
ALTER TABLE files DROP COLUMN IF EXISTS summary;
ALTER TABLE files DROP COLUMN IF EXISTS tags;
DROP EXTENSION IF EXISTS vector;
